data_dir: data
cuda: 6
seed: 0
exps_path: exps
flip_p: 0.5
use_clip: openai/clip-vit-large-patch14
num_epochs: 30
lr: 0.0005
classifier_lr: 0.0005
warmup_ratio: 0.2
batch_size: 8
gradient_accumulation_steps: 4
output_size: 1024
prompt_learning: true
label_smoothing: 0.1
max_frames: 5
unfreeze_last_n_layers: 0
finetune_lr: 1.0e-05
num_context_vision: 8
prompt_depth_vision: 12
dim_context_vision: 1024
num_context_text: 6
prompt_depth_text: 12
dim_context_text: 768
